services:
  mysql:
    image: mysql:8.4
    container_name: weeks1-mysql
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weeks1
      MYSQL_USER: weeks1
      MYSQL_PASSWORD: weeks1
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-hot:
    image: mysql:8.4
    container_name: weeks1-mysql-hot
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weeks1
      MYSQL_USER: weeks1
      MYSQL_PASSWORD: weeks1
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-hot-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7-alpine
    container_name: weeks1-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
  mysql-hot-data:
  redis-data:
