spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3311/weeks1?useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=UTC&rewriteBatchedStatements=true
    username: weeks1
    password: weeks1
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 5000
      max-lifetime: 1800000
  sql:
    init:
      mode: always
      schema-locations: classpath:db/mysql/schema.sql

app:
  index-sync:
    delay-ms: 5000
    batch-size: 2000
  datasource:
    hot:
      jdbc-url: jdbc:mysql://localhost:3312/weeks1?useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=UTC&rewriteBatchedStatements=true
      username: weeks1
      password: weeks1
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 50
        minimum-idle: 20
        connection-timeout: 5000
        max-lifetime: 1800000
